"""
Fix logger — writes self-healing results to ``.utopia/fixes/`` so coding
agents (Claude Code, Codex, etc.) can pick them up and apply permanent fixes.

Each fix produces:
  1. A JSON file with full context (error, original code, fixed code, explanation).
  2. An auto-updated ``FIXES.md`` summary at ``.utopia/FIXES.md`` that agents
     can scan to see what needs to be permanently applied.
"""

import json
import os
import pathlib
import sys
from datetime import datetime, timezone
from typing import Optional


def _find_utopia_dir() -> pathlib.Path:
    """Walk up from cwd to find or create ``.utopia/``."""
    d = pathlib.Path.cwd()
    for _ in range(10):
        candidate = d / ".utopia"
        if candidate.exists() and candidate.is_dir():
            return candidate
        parent = d.parent
        if parent == d:
            break
        d = parent
    # Fallback: create in cwd
    fallback = pathlib.Path.cwd() / ".utopia"
    fallback.mkdir(parents=True, exist_ok=True)
    return fallback


def _get_fixes_dir() -> pathlib.Path:
    fixes = _find_utopia_dir() / "fixes"
    fixes.mkdir(exist_ok=True)
    return fixes


def _rebuild_fixes_md(fixes_dir: pathlib.Path) -> None:
    """Regenerate the FIXES.md summary from all JSON fix files."""
    utopia_dir = fixes_dir.parent
    fix_files = sorted(fixes_dir.glob("*.json"), key=lambda p: p.stat().st_mtime)

    if not fix_files:
        md_path = utopia_dir / "FIXES.md"
        if md_path.exists():
            md_path.unlink()
        return

    pending = []
    applied = []

    for fp in fix_files:
        try:
            record = json.loads(fp.read_text())
        except Exception:
            continue

        entry = {
            "function_name": record.get("function_name", "unknown"),
            "source_file": record.get("source_file", "unknown"),
            "error_type": record.get("error", {}).get("type", "unknown"),
            "error_message": record.get("error", {}).get("message", ""),
            "explanation": record.get("explanation", ""),
            "hot_patch_success": record.get("hot_patch_success", False),
            "status": record.get("status", "pending_review"),
            "timestamp": record.get("timestamp", ""),
            "file": fp.name,
            "original_code": record.get("original_code", ""),
            "fixed_code": record.get("fixed_code", ""),
        }

        if entry["status"] == "applied":
            applied.append(entry)
        else:
            pending.append(entry)

    lines = [
        "# Utopia Self-Healing Fixes",
        "",
        "Auto-generated by the Utopia SDK. Coding agents: apply the pending fixes below,",
        "then delete the corresponding JSON file from `.utopia/fixes/`.",
        "",
    ]

    if pending:
        lines.append(f"## Pending Fixes ({len(pending)})")
        lines.append("")
        for e in pending:
            lines.append(f"### `{e['function_name']}` -- {e['error_type']}")
            lines.append(f"- **File:** `{e['source_file']}`")
            lines.append(f"- **Error:** {e['error_message']}")
            lines.append(f"- **Explanation:** {e['explanation']}")
            patched = "yes" if e["hot_patch_success"] else "no (fix failed at runtime too)"
            lines.append(f"- **Hot-patched at runtime:** {patched}")
            lines.append(f"- **Fix details:** `fixes/{e['file']}`")
            lines.append(f"- **When:** {e['timestamp']}")
            lines.append("")
            lines.append("**Original code:**")
            lines.append("```python")
            lines.append(e["original_code"].rstrip())
            lines.append("```")
            lines.append("")
            lines.append("**Fixed code (apply this):**")
            lines.append("```python")
            lines.append(e["fixed_code"].rstrip())
            lines.append("```")
            lines.append("")

    if applied:
        lines.append(f"## Applied Fixes ({len(applied)})")
        lines.append("")
        for e in applied:
            lines.append(f"- `{e['function_name']}` in `{e['source_file']}` -- {e['explanation']}")
        lines.append("")

    md_path = utopia_dir / "FIXES.md"
    md_path.write_text("\n".join(lines))


def _preserve_decorators(original_code: str, fixed_code: str) -> str:
    """Prepend decorator lines from the original code onto the fixed code.

    The AI-generated fix omits decorators, but agents need them in the
    replacement so they don't accidentally strip ``@utopia`` (or other
    decorators) when applying the fix.
    """
    original_lines = original_code.split("\n")
    decorator_lines = []
    for line in original_lines:
        stripped = line.lstrip()
        if stripped.startswith("@"):
            decorator_lines.append(line)
        elif stripped.startswith("def ") or stripped.startswith("async def "):
            break
        elif stripped == "" or stripped.startswith("#"):
            continue
        else:
            break

    if not decorator_lines:
        return fixed_code

    # Detect indentation of the def line in the fixed code
    for fline in fixed_code.split("\n"):
        if fline.lstrip().startswith("def ") or fline.lstrip().startswith("async def "):
            indent = fline[: len(fline) - len(fline.lstrip())]
            break
    else:
        indent = ""

    # Re-indent decorator lines to match the fixed code
    prefixed = []
    for dl in decorator_lines:
        prefixed.append(indent + dl.lstrip())

    return "\n".join(prefixed) + "\n" + fixed_code


def log_fix(
    function_name: str,
    source_file: str,
    original_code: str,
    fixed_code: str,
    error_type: str,
    error_message: str,
    error_traceback: str,
    explanation: str,
    hot_patch_success: bool,
    patch_error: Optional[str] = None,
) -> Optional[str]:
    """Log a fix to ``.utopia/fixes/`` and update FIXES.md.

    Returns the path to the JSON fix file, or None on failure.
    """
    try:
        # Ensure the fixed code includes decorators from the original
        fixed_code = _preserve_decorators(original_code, fixed_code)

        fixes_dir = _get_fixes_dir()
        ts = datetime.now(timezone.utc)
        timestamp_slug = ts.strftime("%Y%m%d_%H%M%S_%f")
        fix_id = f"{function_name}_{timestamp_slug}"

        fix_record = {
            "id": fix_id,
            "timestamp": ts.isoformat(),
            "function_name": function_name,
            "source_file": os.path.abspath(source_file),
            "error": {
                "type": error_type,
                "message": error_message,
                "traceback": error_traceback,
            },
            "original_code": original_code,
            "fixed_code": fixed_code,
            "explanation": explanation,
            "hot_patch_success": hot_patch_success,
            "patch_error": patch_error,
            "status": "pending_review",
        }

        json_path = fixes_dir / f"{fix_id}.json"
        json_path.write_text(json.dumps(fix_record, indent=2))

        # Update the summary
        _rebuild_fixes_md(fixes_dir)

        # Print to stderr so the developer sees it
        label = "healed" if hot_patch_success else "fix generated (hot-patch failed)"
        print(
            f"[utopia] {label}: {function_name} -- {error_type}: {error_message}",
            file=sys.stderr,
        )
        print(
            f"[utopia] fix logged to {json_path}",
            file=sys.stderr,
        )

        return str(json_path)

    except Exception:
        return None
